---
- name: Install Nginx and deploy Hello World page
  hosts: ansible
  become: yes

  vars:
    nginx_html_root: "/usr/share/nginx/html"
    nginx_server_name: "Nginx Server"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create /etc/nginx directory
      file:
        path: /etc/nginx
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy HTML file to Nginx root
      copy:
        src: index.html
        dest: "/usr/share/nginx/html/index.html"
        owner: root
        group: root
        mode: '0644'

    - name: Template nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
